### ISSUE TITLE
Building, OpenNI issue

### ISSUE THREAD

**Issue by petrasvestartas** [danielTobon43/pointcloudToMesh#3]
Hi,

I finally managed to install PCL on windows.

Through CMake I compile the VS project.
Build is successful.

But when I run the app in debug mode, I have error regarding OpenNI.
How can I solve it ?

![image](https://user-images.githubusercontent.com/18013985/100545959-e8dc5300-325e-11eb-8a2f-7188314a78e3.png)

```
C:\libs\PCL\pointcloudToMesh-master\src\bin\Debug\pointcloudToMESH.exe (process 24840) exited with code -1073741515.
Press any key to close this window . . .
```

I also tried this by copying stl file to debug folder:
![image](https://user-images.githubusercontent.com/18013985/100546954-6c4c7300-3264-11eb-8b3e-73adcab4e3a0.png)

**Comment by ghost** [comment]
Hi @petrasvestartas. 

Unfortunately is an error related to your PCL installation, I can't help you. Besides, I made the project to compile with CMake, so you don't need MS visual studio in windows. 

I don't know what is your project or application. Do you need a program to convert a .pcd file to mesh? if so, you can search a standalone version for windows that you can install normaly.

This program is for someone that needs to integrate such functionality in their project or app.

Best regards,

Daniel

**Comment by ghost** [comment]
> Hi @petrasvestartas.
> 
> Unfortunately is an error related to your PCL installation, I can't help you. Besides, I made the project to compile with CMake, so you don't need MS visual studio in windows.
> 
> I don't know what is your project or application. Do you need a program to convert a .pcd file to mesh? if so, you can search a standalone version for windows that you can install normaly.
> 
> This program is for someone that needs to integrate such functionality in their project or app.
> 
> Best regards,
> 
> Daniel

**Comment by tiancaipipi110** [comment]
@danielTobon43  Is this expected behavior on mls normal estimation? 
```
Found pcd file.
[done, 2.2609e+07 ms : 35947 points]
Using mls method estimation...[OK]
[pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!
Applying surface meshing...Using surface method: gp3 ...
[pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!
```
